"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
type Role = { role_code: string; role_name: string; role_assignment_id: string; scope_type?: string | null };
export default function SSOCallbackPage() {
  const params = useSearchParams(); const router = useRouter(); const [message, setMessage] = useState("Completing secure sign-in…"); const [handoff, setHandoff] = useState(""); const [roles, setRoles] = useState<Role[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { const code = params.get("code"), state = params.get("state"), error = params.get("error"); if (error) { setMessage(`Identity provider error: ${error}`); return; } if (!code || !state) { setMessage("The identity provider callback is incomplete."); return; } void fetch("/api/session/sso/callback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ code, state }) }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.detail || "SSO callback failed."); setHandoff(data.handoff_token); setRoles(data.available_roles || []); setMessage("Choose the role for this session."); }).catch((err) => setMessage(err.message)); }, [params]);
  async function exchange(roleCode: string) { setBusy(true); const response = await fetch("/api/session/sso/exchange", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ handoff_token: handoff, role_code: roleCode, device_label: "Web browser" }) }); const data = await response.json().catch(() => ({})); if (response.ok) { router.replace("/"); router.refresh(); return; } setMessage(data.detail || "The role session could not be created."); setBusy(false); }
  return <main className="auth-page"><section className="auth-card"><div className="brand-mark">LS</div><span className="eyebrow">Institution SSO</span><h1>Secure sign-in</h1><p>{message}</p>{roles.map((role) => <button key={role.role_assignment_id} className="submit-button" disabled={busy} onClick={() => void exchange(role.role_code)}>{role.role_name}{role.scope_type ? ` — ${role.scope_type}` : ""}</button>)}</section></main>;
}
